services:
  postgres:
    image: postgres:18
    container_name: toeic-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: toeic
      POSTGRES_PASSWORD: toeic_dev_password
      POSTGRES_DB: toeic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
